(cl:defpackage RMPISR-srv
  (:use )
  (:export
   "ADDPOINT"
   "<ADDPOINT-REQUEST>"
   "ADDPOINT-REQUEST"
   "<ADDPOINT-RESPONSE>"
   "ADDPOINT-RESPONSE"
   "GO"
   "<GO-REQUEST>"
   "GO-REQUEST"
   "<GO-RESPONSE>"
   "GO-RESPONSE"
   "STOP"
   "<STOP-REQUEST>"
   "STOP-REQUEST"
   "<STOP-RESPONSE>"
   "STOP-RESPONSE"
  ))

