// Generated by gencpp from file RMPISR/markerdetected.msg
// DO NOT EDIT!


#ifndef RMPISR_MESSAGE_MARKERDETECTED_H
#define RMPISR_MESSAGE_MARKERDETECTED_H

#include <ros/service_traits.h>


#include <RMPISR/markerdetectedRequest.h>
#include <RMPISR/markerdetectedResponse.h>


namespace RMPISR
{

struct markerdetected
{

typedef markerdetectedRequest Request;
typedef markerdetectedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct markerdetected
} // namespace RMPISR


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::RMPISR::markerdetected > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::RMPISR::markerdetected&) { return value(); }
};

template<>
struct DataType< ::RMPISR::markerdetected > {
  static const char* value()
  {
    return "RMPISR/markerdetected";
  }

  static const char* value(const ::RMPISR::markerdetected&) { return value(); }
};


// service_traits::MD5Sum< ::RMPISR::markerdetectedRequest> should match 
// service_traits::MD5Sum< ::RMPISR::markerdetected > 
template<>
struct MD5Sum< ::RMPISR::markerdetectedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::RMPISR::markerdetected >::value();
  }
  static const char* value(const ::RMPISR::markerdetectedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::RMPISR::markerdetectedRequest> should match 
// service_traits::DataType< ::RMPISR::markerdetected > 
template<>
struct DataType< ::RMPISR::markerdetectedRequest>
{
  static const char* value()
  {
    return DataType< ::RMPISR::markerdetected >::value();
  }
  static const char* value(const ::RMPISR::markerdetectedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::RMPISR::markerdetectedResponse> should match 
// service_traits::MD5Sum< ::RMPISR::markerdetected > 
template<>
struct MD5Sum< ::RMPISR::markerdetectedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::RMPISR::markerdetected >::value();
  }
  static const char* value(const ::RMPISR::markerdetectedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::RMPISR::markerdetectedResponse> should match 
// service_traits::DataType< ::RMPISR::markerdetected > 
template<>
struct DataType< ::RMPISR::markerdetectedResponse>
{
  static const char* value()
  {
    return DataType< ::RMPISR::markerdetected >::value();
  }
  static const char* value(const ::RMPISR::markerdetectedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RMPISR_MESSAGE_MARKERDETECTED_H
