// Generated by gencpp from file RMPISR/stop.msg
// DO NOT EDIT!


#ifndef RMPISR_MESSAGE_STOP_H
#define RMPISR_MESSAGE_STOP_H

#include <ros/service_traits.h>


#include <RMPISR/stopRequest.h>
#include <RMPISR/stopResponse.h>


namespace RMPISR
{

struct stop
{

typedef stopRequest Request;
typedef stopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct stop
} // namespace RMPISR


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::RMPISR::stop > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::RMPISR::stop&) { return value(); }
};

template<>
struct DataType< ::RMPISR::stop > {
  static const char* value()
  {
    return "RMPISR/stop";
  }

  static const char* value(const ::RMPISR::stop&) { return value(); }
};


// service_traits::MD5Sum< ::RMPISR::stopRequest> should match 
// service_traits::MD5Sum< ::RMPISR::stop > 
template<>
struct MD5Sum< ::RMPISR::stopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::RMPISR::stop >::value();
  }
  static const char* value(const ::RMPISR::stopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::RMPISR::stopRequest> should match 
// service_traits::DataType< ::RMPISR::stop > 
template<>
struct DataType< ::RMPISR::stopRequest>
{
  static const char* value()
  {
    return DataType< ::RMPISR::stop >::value();
  }
  static const char* value(const ::RMPISR::stopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::RMPISR::stopResponse> should match 
// service_traits::MD5Sum< ::RMPISR::stop > 
template<>
struct MD5Sum< ::RMPISR::stopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::RMPISR::stop >::value();
  }
  static const char* value(const ::RMPISR::stopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::RMPISR::stopResponse> should match 
// service_traits::DataType< ::RMPISR::stop > 
template<>
struct DataType< ::RMPISR::stopResponse>
{
  static const char* value()
  {
    return DataType< ::RMPISR::stop >::value();
  }
  static const char* value(const ::RMPISR::stopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RMPISR_MESSAGE_STOP_H
