set(_CATKIN_CURRENT_PACKAGE "segway_rmp")
set(segway_rmp_VERSION "0.1.2")
set(segway_rmp_MAINTAINER "William Woodall <wjwwood@gmail.com>, Piyush Khandelwal <piyushk@gmail.com>")
set(segway_rmp_PACKAGE_FORMAT "1")
set(segway_rmp_BUILD_DEPENDS "geometry_msgs" "libsegwayrmp" "message_generation" "nav_msgs" "roscpp" "serial" "std_msgs" "tf")
set(segway_rmp_BUILD_EXPORT_DEPENDS "geometry_msgs" "libsegwayrmp" "message_runtime" "nav_msgs" "roscpp" "serial" "std_msgs" "tf")
set(segway_rmp_BUILDTOOL_DEPENDS "catkin")
set(segway_rmp_BUILDTOOL_EXPORT_DEPENDS )
set(segway_rmp_EXEC_DEPENDS "geometry_msgs" "libsegwayrmp" "message_runtime" "nav_msgs" "roscpp" "serial" "std_msgs" "tf")
set(segway_rmp_RUN_DEPENDS "geometry_msgs" "libsegwayrmp" "message_runtime" "nav_msgs" "roscpp" "serial" "std_msgs" "tf")
set(segway_rmp_TEST_DEPENDS )
set(segway_rmp_DOC_DEPENDS )
set(segway_rmp_URL_WEBSITE "http://ros.org/wiki/segway_rmp")
set(segway_rmp_URL_BUGTRACKER "https://github.com/segwayrmp/segway-rmp-ros-pkg/issues")
set(segway_rmp_URL_REPOSITORY "https://github.com/segwayrmp/segway-rmp-ros-pkg")
set(segway_rmp_DEPRECATED "")