// Generated by gencpp from file testeturtle/go.msg
// DO NOT EDIT!


#ifndef TESTETURTLE_MESSAGE_GO_H
#define TESTETURTLE_MESSAGE_GO_H

#include <ros/service_traits.h>


#include <testeturtle/goRequest.h>
#include <testeturtle/goResponse.h>


namespace testeturtle
{

struct go
{

typedef goRequest Request;
typedef goResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct go
} // namespace testeturtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::testeturtle::go > {
  static const char* value()
  {
    return "7a2f37ef2ba405f0c7a15cc72663d6f0";
  }

  static const char* value(const ::testeturtle::go&) { return value(); }
};

template<>
struct DataType< ::testeturtle::go > {
  static const char* value()
  {
    return "testeturtle/go";
  }

  static const char* value(const ::testeturtle::go&) { return value(); }
};


// service_traits::MD5Sum< ::testeturtle::goRequest> should match 
// service_traits::MD5Sum< ::testeturtle::go > 
template<>
struct MD5Sum< ::testeturtle::goRequest>
{
  static const char* value()
  {
    return MD5Sum< ::testeturtle::go >::value();
  }
  static const char* value(const ::testeturtle::goRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::testeturtle::goRequest> should match 
// service_traits::DataType< ::testeturtle::go > 
template<>
struct DataType< ::testeturtle::goRequest>
{
  static const char* value()
  {
    return DataType< ::testeturtle::go >::value();
  }
  static const char* value(const ::testeturtle::goRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::testeturtle::goResponse> should match 
// service_traits::MD5Sum< ::testeturtle::go > 
template<>
struct MD5Sum< ::testeturtle::goResponse>
{
  static const char* value()
  {
    return MD5Sum< ::testeturtle::go >::value();
  }
  static const char* value(const ::testeturtle::goResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::testeturtle::goResponse> should match 
// service_traits::DataType< ::testeturtle::go > 
template<>
struct DataType< ::testeturtle::goResponse>
{
  static const char* value()
  {
    return DataType< ::testeturtle::go >::value();
  }
  static const char* value(const ::testeturtle::goResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTETURTLE_MESSAGE_GO_H
