# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from RMPISR/sensors.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class sensors(genpy.Message):
  _md5sum = "9eedb779141fc8e42c127e038f10520e"
  _type = "RMPISR/sensors"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 ir1
uint8 ir2
uint8 ir3
uint8 ir4
uint8 s1
uint8 s2
uint8 s5
"""
  __slots__ = ['ir1','ir2','ir3','ir4','s1','s2','s5']
  _slot_types = ['uint8','uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ir1,ir2,ir3,ir4,s1,s2,s5

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sensors, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ir1 is None:
        self.ir1 = 0
      if self.ir2 is None:
        self.ir2 = 0
      if self.ir3 is None:
        self.ir3 = 0
      if self.ir4 is None:
        self.ir4 = 0
      if self.s1 is None:
        self.s1 = 0
      if self.s2 is None:
        self.s2 = 0
      if self.s5 is None:
        self.s5 = 0
    else:
      self.ir1 = 0
      self.ir2 = 0
      self.ir3 = 0
      self.ir4 = 0
      self.s1 = 0
      self.s2 = 0
      self.s5 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7B().pack(_x.ir1, _x.ir2, _x.ir3, _x.ir4, _x.s1, _x.s2, _x.s5))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.ir1, _x.ir2, _x.ir3, _x.ir4, _x.s1, _x.s2, _x.s5,) = _get_struct_7B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7B().pack(_x.ir1, _x.ir2, _x.ir3, _x.ir4, _x.s1, _x.s2, _x.s5))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.ir1, _x.ir2, _x.ir3, _x.ir4, _x.s1, _x.s2, _x.s5,) = _get_struct_7B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7B = None
def _get_struct_7B():
    global _struct_7B
    if _struct_7B is None:
        _struct_7B = struct.Struct("<7B")
    return _struct_7B
