// Generated by gencpp from file testeturtle/stop.msg
// DO NOT EDIT!


#ifndef TESTETURTLE_MESSAGE_STOP_H
#define TESTETURTLE_MESSAGE_STOP_H

#include <ros/service_traits.h>


#include <testeturtle/stopRequest.h>
#include <testeturtle/stopResponse.h>


namespace testeturtle
{

struct stop
{

typedef stopRequest Request;
typedef stopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct stop
} // namespace testeturtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::testeturtle::stop > {
  static const char* value()
  {
    return "7a2f37ef2ba405f0c7a15cc72663d6f0";
  }

  static const char* value(const ::testeturtle::stop&) { return value(); }
};

template<>
struct DataType< ::testeturtle::stop > {
  static const char* value()
  {
    return "testeturtle/stop";
  }

  static const char* value(const ::testeturtle::stop&) { return value(); }
};


// service_traits::MD5Sum< ::testeturtle::stopRequest> should match 
// service_traits::MD5Sum< ::testeturtle::stop > 
template<>
struct MD5Sum< ::testeturtle::stopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::testeturtle::stop >::value();
  }
  static const char* value(const ::testeturtle::stopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::testeturtle::stopRequest> should match 
// service_traits::DataType< ::testeturtle::stop > 
template<>
struct DataType< ::testeturtle::stopRequest>
{
  static const char* value()
  {
    return DataType< ::testeturtle::stop >::value();
  }
  static const char* value(const ::testeturtle::stopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::testeturtle::stopResponse> should match 
// service_traits::MD5Sum< ::testeturtle::stop > 
template<>
struct MD5Sum< ::testeturtle::stopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::testeturtle::stop >::value();
  }
  static const char* value(const ::testeturtle::stopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::testeturtle::stopResponse> should match 
// service_traits::DataType< ::testeturtle::stop > 
template<>
struct DataType< ::testeturtle::stopResponse>
{
  static const char* value()
  {
    return DataType< ::testeturtle::stop >::value();
  }
  static const char* value(const ::testeturtle::stopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TESTETURTLE_MESSAGE_STOP_H
