// Generated by gencpp from file RMPISR/arrivedDestiny.msg
// DO NOT EDIT!


#ifndef RMPISR_MESSAGE_ARRIVEDDESTINY_H
#define RMPISR_MESSAGE_ARRIVEDDESTINY_H

#include <ros/service_traits.h>


#include <RMPISR/arrivedDestinyRequest.h>
#include <RMPISR/arrivedDestinyResponse.h>


namespace RMPISR
{

struct arrivedDestiny
{

typedef arrivedDestinyRequest Request;
typedef arrivedDestinyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct arrivedDestiny
} // namespace RMPISR


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::RMPISR::arrivedDestiny > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::RMPISR::arrivedDestiny&) { return value(); }
};

template<>
struct DataType< ::RMPISR::arrivedDestiny > {
  static const char* value()
  {
    return "RMPISR/arrivedDestiny";
  }

  static const char* value(const ::RMPISR::arrivedDestiny&) { return value(); }
};


// service_traits::MD5Sum< ::RMPISR::arrivedDestinyRequest> should match 
// service_traits::MD5Sum< ::RMPISR::arrivedDestiny > 
template<>
struct MD5Sum< ::RMPISR::arrivedDestinyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::RMPISR::arrivedDestiny >::value();
  }
  static const char* value(const ::RMPISR::arrivedDestinyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::RMPISR::arrivedDestinyRequest> should match 
// service_traits::DataType< ::RMPISR::arrivedDestiny > 
template<>
struct DataType< ::RMPISR::arrivedDestinyRequest>
{
  static const char* value()
  {
    return DataType< ::RMPISR::arrivedDestiny >::value();
  }
  static const char* value(const ::RMPISR::arrivedDestinyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::RMPISR::arrivedDestinyResponse> should match 
// service_traits::MD5Sum< ::RMPISR::arrivedDestiny > 
template<>
struct MD5Sum< ::RMPISR::arrivedDestinyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::RMPISR::arrivedDestiny >::value();
  }
  static const char* value(const ::RMPISR::arrivedDestinyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::RMPISR::arrivedDestinyResponse> should match 
// service_traits::DataType< ::RMPISR::arrivedDestiny > 
template<>
struct DataType< ::RMPISR::arrivedDestinyResponse>
{
  static const char* value()
  {
    return DataType< ::RMPISR::arrivedDestiny >::value();
  }
  static const char* value(const ::RMPISR::arrivedDestinyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RMPISR_MESSAGE_ARRIVEDDESTINY_H
