// Generated by gencpp from file RMPISR/go.msg
// DO NOT EDIT!


#ifndef RMPISR_MESSAGE_GO_H
#define RMPISR_MESSAGE_GO_H

#include <ros/service_traits.h>


#include <RMPISR/goRequest.h>
#include <RMPISR/goResponse.h>


namespace RMPISR
{

struct go
{

typedef goRequest Request;
typedef goResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct go
} // namespace RMPISR


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::RMPISR::go > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::RMPISR::go&) { return value(); }
};

template<>
struct DataType< ::RMPISR::go > {
  static const char* value()
  {
    return "RMPISR/go";
  }

  static const char* value(const ::RMPISR::go&) { return value(); }
};


// service_traits::MD5Sum< ::RMPISR::goRequest> should match 
// service_traits::MD5Sum< ::RMPISR::go > 
template<>
struct MD5Sum< ::RMPISR::goRequest>
{
  static const char* value()
  {
    return MD5Sum< ::RMPISR::go >::value();
  }
  static const char* value(const ::RMPISR::goRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::RMPISR::goRequest> should match 
// service_traits::DataType< ::RMPISR::go > 
template<>
struct DataType< ::RMPISR::goRequest>
{
  static const char* value()
  {
    return DataType< ::RMPISR::go >::value();
  }
  static const char* value(const ::RMPISR::goRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::RMPISR::goResponse> should match 
// service_traits::MD5Sum< ::RMPISR::go > 
template<>
struct MD5Sum< ::RMPISR::goResponse>
{
  static const char* value()
  {
    return MD5Sum< ::RMPISR::go >::value();
  }
  static const char* value(const ::RMPISR::goResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::RMPISR::goResponse> should match 
// service_traits::DataType< ::RMPISR::go > 
template<>
struct DataType< ::RMPISR::goResponse>
{
  static const char* value()
  {
    return DataType< ::RMPISR::go >::value();
  }
  static const char* value(const ::RMPISR::goResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RMPISR_MESSAGE_GO_H
