// Generated by gencpp from file RMPISR/odomError.msg
// DO NOT EDIT!


#ifndef RMPISR_MESSAGE_ODOMERROR_H
#define RMPISR_MESSAGE_ODOMERROR_H

#include <ros/service_traits.h>


#include <RMPISR/odomErrorRequest.h>
#include <RMPISR/odomErrorResponse.h>


namespace RMPISR
{

struct odomError
{

typedef odomErrorRequest Request;
typedef odomErrorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct odomError
} // namespace RMPISR


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::RMPISR::odomError > {
  static const char* value()
  {
    return "f759b8f7398989ae2c04da536ffa12af";
  }

  static const char* value(const ::RMPISR::odomError&) { return value(); }
};

template<>
struct DataType< ::RMPISR::odomError > {
  static const char* value()
  {
    return "RMPISR/odomError";
  }

  static const char* value(const ::RMPISR::odomError&) { return value(); }
};


// service_traits::MD5Sum< ::RMPISR::odomErrorRequest> should match 
// service_traits::MD5Sum< ::RMPISR::odomError > 
template<>
struct MD5Sum< ::RMPISR::odomErrorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::RMPISR::odomError >::value();
  }
  static const char* value(const ::RMPISR::odomErrorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::RMPISR::odomErrorRequest> should match 
// service_traits::DataType< ::RMPISR::odomError > 
template<>
struct DataType< ::RMPISR::odomErrorRequest>
{
  static const char* value()
  {
    return DataType< ::RMPISR::odomError >::value();
  }
  static const char* value(const ::RMPISR::odomErrorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::RMPISR::odomErrorResponse> should match 
// service_traits::MD5Sum< ::RMPISR::odomError > 
template<>
struct MD5Sum< ::RMPISR::odomErrorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::RMPISR::odomError >::value();
  }
  static const char* value(const ::RMPISR::odomErrorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::RMPISR::odomErrorResponse> should match 
// service_traits::DataType< ::RMPISR::odomError > 
template<>
struct DataType< ::RMPISR::odomErrorResponse>
{
  static const char* value()
  {
    return DataType< ::RMPISR::odomError >::value();
  }
  static const char* value(const ::RMPISR::odomErrorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RMPISR_MESSAGE_ODOMERROR_H
