// Generated by gencpp from file RMPISR/resetrmp.msg
// DO NOT EDIT!


#ifndef RMPISR_MESSAGE_RESETRMP_H
#define RMPISR_MESSAGE_RESETRMP_H

#include <ros/service_traits.h>


#include <RMPISR/resetrmpRequest.h>
#include <RMPISR/resetrmpResponse.h>


namespace RMPISR
{

struct resetrmp
{

typedef resetrmpRequest Request;
typedef resetrmpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct resetrmp
} // namespace RMPISR


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::RMPISR::resetrmp > {
  static const char* value()
  {
    return "f759b8f7398989ae2c04da536ffa12af";
  }

  static const char* value(const ::RMPISR::resetrmp&) { return value(); }
};

template<>
struct DataType< ::RMPISR::resetrmp > {
  static const char* value()
  {
    return "RMPISR/resetrmp";
  }

  static const char* value(const ::RMPISR::resetrmp&) { return value(); }
};


// service_traits::MD5Sum< ::RMPISR::resetrmpRequest> should match 
// service_traits::MD5Sum< ::RMPISR::resetrmp > 
template<>
struct MD5Sum< ::RMPISR::resetrmpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::RMPISR::resetrmp >::value();
  }
  static const char* value(const ::RMPISR::resetrmpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::RMPISR::resetrmpRequest> should match 
// service_traits::DataType< ::RMPISR::resetrmp > 
template<>
struct DataType< ::RMPISR::resetrmpRequest>
{
  static const char* value()
  {
    return DataType< ::RMPISR::resetrmp >::value();
  }
  static const char* value(const ::RMPISR::resetrmpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::RMPISR::resetrmpResponse> should match 
// service_traits::MD5Sum< ::RMPISR::resetrmp > 
template<>
struct MD5Sum< ::RMPISR::resetrmpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::RMPISR::resetrmp >::value();
  }
  static const char* value(const ::RMPISR::resetrmpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::RMPISR::resetrmpResponse> should match 
// service_traits::DataType< ::RMPISR::resetrmp > 
template<>
struct DataType< ::RMPISR::resetrmpResponse>
{
  static const char* value()
  {
    return DataType< ::RMPISR::resetrmp >::value();
  }
  static const char* value(const ::RMPISR::resetrmpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RMPISR_MESSAGE_RESETRMP_H
