// Generated by gencpp from file RMPISR/stopRequest.msg
// DO NOT EDIT!


#ifndef RMPISR_MESSAGE_STOPREQUEST_H
#define RMPISR_MESSAGE_STOPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace RMPISR
{
template <class ContainerAllocator>
struct stopRequest_
{
  typedef stopRequest_<ContainerAllocator> Type;

  stopRequest_()
    : size(0)
    , pointArray()  {
    }
  stopRequest_(const ContainerAllocator& _alloc)
    : size(0)
    , pointArray(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _size_type;
  _size_type size;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pointArray_type;
  _pointArray_type pointArray;




  typedef boost::shared_ptr< ::RMPISR::stopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RMPISR::stopRequest_<ContainerAllocator> const> ConstPtr;

}; // struct stopRequest_

typedef ::RMPISR::stopRequest_<std::allocator<void> > stopRequest;

typedef boost::shared_ptr< ::RMPISR::stopRequest > stopRequestPtr;
typedef boost::shared_ptr< ::RMPISR::stopRequest const> stopRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RMPISR::stopRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RMPISR::stopRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RMPISR

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RMPISR::stopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RMPISR::stopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RMPISR::stopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RMPISR::stopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RMPISR::stopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RMPISR::stopRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RMPISR::stopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5bbea48bfb057c91b7a5e97f25876fc2";
  }

  static const char* value(const ::RMPISR::stopRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5bbea48bfb057c91ULL;
  static const uint64_t static_value2 = 0xb7a5e97f25876fc2ULL;
};

template<class ContainerAllocator>
struct DataType< ::RMPISR::stopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RMPISR/stopRequest";
  }

  static const char* value(const ::RMPISR::stopRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RMPISR::stopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 size\n\
geometry_msgs/Point pointArray\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::RMPISR::stopRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RMPISR::stopRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.size);
      stream.next(m.pointArray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stopRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RMPISR::stopRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RMPISR::stopRequest_<ContainerAllocator>& v)
  {
    s << indent << "size: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.size);
    s << indent << "pointArray: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pointArray);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RMPISR_MESSAGE_STOPREQUEST_H
