// Generated by gencpp from file perception_pkg/add_obstacle.msg
// DO NOT EDIT!


#ifndef PERCEPTION_PKG_MESSAGE_ADD_OBSTACLE_H
#define PERCEPTION_PKG_MESSAGE_ADD_OBSTACLE_H

#include <ros/service_traits.h>


#include <perception_pkg/add_obstacleRequest.h>
#include <perception_pkg/add_obstacleResponse.h>


namespace perception_pkg
{

struct add_obstacle
{

typedef add_obstacleRequest Request;
typedef add_obstacleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add_obstacle
} // namespace perception_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::perception_pkg::add_obstacle > {
  static const char* value()
  {
    return "f8fb8420bfa4e803c844225154ef8e5f";
  }

  static const char* value(const ::perception_pkg::add_obstacle&) { return value(); }
};

template<>
struct DataType< ::perception_pkg::add_obstacle > {
  static const char* value()
  {
    return "perception_pkg/add_obstacle";
  }

  static const char* value(const ::perception_pkg::add_obstacle&) { return value(); }
};


// service_traits::MD5Sum< ::perception_pkg::add_obstacleRequest> should match 
// service_traits::MD5Sum< ::perception_pkg::add_obstacle > 
template<>
struct MD5Sum< ::perception_pkg::add_obstacleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::perception_pkg::add_obstacle >::value();
  }
  static const char* value(const ::perception_pkg::add_obstacleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::perception_pkg::add_obstacleRequest> should match 
// service_traits::DataType< ::perception_pkg::add_obstacle > 
template<>
struct DataType< ::perception_pkg::add_obstacleRequest>
{
  static const char* value()
  {
    return DataType< ::perception_pkg::add_obstacle >::value();
  }
  static const char* value(const ::perception_pkg::add_obstacleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::perception_pkg::add_obstacleResponse> should match 
// service_traits::MD5Sum< ::perception_pkg::add_obstacle > 
template<>
struct MD5Sum< ::perception_pkg::add_obstacleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::perception_pkg::add_obstacle >::value();
  }
  static const char* value(const ::perception_pkg::add_obstacleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::perception_pkg::add_obstacleResponse> should match 
// service_traits::DataType< ::perception_pkg::add_obstacle > 
template<>
struct DataType< ::perception_pkg::add_obstacleResponse>
{
  static const char* value()
  {
    return DataType< ::perception_pkg::add_obstacle >::value();
  }
  static const char* value(const ::perception_pkg::add_obstacleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PERCEPTION_PKG_MESSAGE_ADD_OBSTACLE_H
