// Generated by gencpp from file perception_pkg/add_obstacleRequest.msg
// DO NOT EDIT!


#ifndef PERCEPTION_PKG_MESSAGE_ADD_OBSTACLEREQUEST_H
#define PERCEPTION_PKG_MESSAGE_ADD_OBSTACLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception_pkg
{
template <class ContainerAllocator>
struct add_obstacleRequest_
{
  typedef add_obstacleRequest_<ContainerAllocator> Type;

  add_obstacleRequest_()
    : xobj(0.0)
    , yobj(0.0)  {
    }
  add_obstacleRequest_(const ContainerAllocator& _alloc)
    : xobj(0.0)
    , yobj(0.0)  {
  (void)_alloc;
    }



   typedef float _xobj_type;
  _xobj_type xobj;

   typedef float _yobj_type;
  _yobj_type yobj;





  typedef boost::shared_ptr< ::perception_pkg::add_obstacleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_pkg::add_obstacleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct add_obstacleRequest_

typedef ::perception_pkg::add_obstacleRequest_<std::allocator<void> > add_obstacleRequest;

typedef boost::shared_ptr< ::perception_pkg::add_obstacleRequest > add_obstacleRequestPtr;
typedef boost::shared_ptr< ::perception_pkg::add_obstacleRequest const> add_obstacleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_pkg::add_obstacleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_pkg::add_obstacleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_pkg::add_obstacleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_pkg::add_obstacleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_pkg::add_obstacleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_pkg::add_obstacleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_pkg::add_obstacleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_pkg::add_obstacleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_pkg::add_obstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8fb8420bfa4e803c844225154ef8e5f";
  }

  static const char* value(const ::perception_pkg::add_obstacleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8fb8420bfa4e803ULL;
  static const uint64_t static_value2 = 0xc844225154ef8e5fULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_pkg::add_obstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_pkg/add_obstacleRequest";
  }

  static const char* value(const ::perception_pkg::add_obstacleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_pkg::add_obstacleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 xobj\n\
float32 yobj\n\
\n\
";
  }

  static const char* value(const ::perception_pkg::add_obstacleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_pkg::add_obstacleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xobj);
      stream.next(m.yobj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct add_obstacleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_pkg::add_obstacleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_pkg::add_obstacleRequest_<ContainerAllocator>& v)
  {
    s << indent << "xobj: ";
    Printer<float>::stream(s, indent + "  ", v.xobj);
    s << indent << "yobj: ";
    Printer<float>::stream(s, indent + "  ", v.yobj);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_PKG_MESSAGE_ADD_OBSTACLEREQUEST_H
